apps/workshop/urls.py
from django.urls import path
from apps.workshop.views.workshop import workshop

app_name = "workshop"

urlpatterns = [
    path("workshop/list/", workshop.WorkshopListView.as_view(), name="workshop_list"),
    path(
        "workshop/create/",
        workshop.WorkshopCreateView.as_view(),
        name="workshop_create",
    ),
    path(
        "workshop/<uuid:pk>/update/",
        workshop.WorkshopUpdateView.as_view(),
        name="workshop_update",
    ),
    path(
        "workshop/<uuid:pk>/delete/",
        workshop.WorkshopDeleteView.as_view(),
        name="workshop_delete",
    ),
    path(
        "workshop/<uuid:pk>/detail/",
        workshop.WorkshopDetailView.as_view(),
        name="workshop_detail",
    ),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("", include("apps.address.urls")),
    path("", include("apps.person.urls")),
    path("", include("apps.farm.urls")),
    path("", include("apps.employee.urls")),
    path("", include("apps.workshop.urls")),
    path("", include("apps.vehicle.urls")),
    path("", include("apps.inventory.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/workshop/models.py
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models
from apps.farm.models import Farm
from apps.core.models import Base
from django.db.models import UniqueConstraint


class Workshop(Base, models.Model):
    name = models.CharField(_("name"), max_length=50)
    farm = models.ForeignKey(
        Farm,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="farm_workshop",
    )

    class Meta:
        verbose_name = _("Workshop")
        ordering = ["-created_at"]

        constraints = [
            UniqueConstraint(
                "name",
                "farm",
                name="unique_farm_workshop_name",
            ),
        ]

    def get_absolute_url(self):
        return reverse("workshop:workshop_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

apps/workshop/forms.py
from django.forms import ModelForm
from apps.workshop.models import Workshop


class WorkshopForm(ModelForm):
    class Meta:
        model = Workshop
        fields = ("name", "farm")

apps/workshop/templates/workshop/workshop_detail.html
<h1>Detalhes</h1>
    <ul>
        <li>Nome: {{ object.name }}</li>
        <li>Proprietario: {{ object.owner }}</li>
        <li>Gerente: {{ object.manager }}</li>
        <li>Localização: {{ object.location }}</li>
        <li>Tamanho HC: {{ object.size_hc }}</li>
        <li>Lat/Long: {{ object.latitude }} - {{ object.longitute }}</li>
    </ul>

apps/workshop/templates/workshop/workshop_form.html
<form  method="post" action=".">

    {% csrf_token %}
    {{ form }}
    <input type="submit"> Salvar</button>

</form>

apps/workshop/templates/workshop/workshop_list.html
<style>
    li {
        box-sizing: border-box;
        padding-bottom: 20px;
    }
</style>

<table>
    <thead>
        <th>Oficina</th>
        <th>Fazenda</th>
        <th>Ações</th>
    </thead>
    <tbody>
        {% for workshop in object_list %}
        <tr>
            <td>{{ workshop.name }}</td>
            <td>{{ workshop.farm }}</td>
            <td>
                <a href="{% url 'workshop:workshop_update' workshop.pk %}" ><strong>EDIT</strong></a>
                <a href="{% url 'workshop:workshop_delete' workshop.pk %}" ><strong>DELETE</strong></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>