apps/farm/urls.py
from django.urls import path
from apps.farm.views.farm import farm
from apps.farm.views.department import department

app_name = "farm"

urlpatterns = [
    path("farm/list/", farm.FarmListView.as_view(), name="farm_list"),
    path("farm/create/", farm.FarmCreateView.as_view(), name="farm_create"),
    path("farm/<uuid:pk>/update/", farm.FarmUpdateView.as_view(), name="farm_update"),
    path("farm/<uuid:pk>/delete/", farm.FarmDeleteView.as_view(), name="farm_delete"),
    path("farm/<uuid:pk>/detail/", farm.FarmDetailView.as_view(), name="farm_detail"),
    path(
        "department/list/",
        department.DepartmentListView.as_view(),
        name="department_list",
    ),
    path(
        "department/create/",
        department.DepartmentCreateView.as_view(),
        name="department_create",
    ),
    path(
        "department/<uuid:pk>/update/",
        department.DepartmentUpdateView.as_view(),
        name="department_update",
    ),
    path(
        "department/<uuid:pk>/delete/",
        department.DepartmentDeleteView.as_view(),
        name="department_delete",
    ),
    path(
        "department/<uuid:pk>/detail/",
        department.DepartmentDetailView.as_view(),
        name="department_detail",
    ),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("", include("apps.address.urls")),
    path("", include("apps.person.urls")),
    path("", include("apps.farm.urls")),
    path("", include("apps.employee.urls")),
    path("", include("apps.workshop.urls")),
    path("", include("apps.vehicle.urls")),
    path("", include("apps.inventory.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/farm/models.py
from django.db import models
from django.urls import reverse
from apps.core.models import Base
from django.utils.translation import gettext_lazy as _
from apps.person.models import Person
from apps.address.models import Address


class Farm(Base, models.Model):
    name = models.CharField(_("Name"), max_length=150)
    owner = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        related_name="farm_owner",
        blank=True,
        null=True,
        verbose_name=_("Owner"),
    )
    manager = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        related_name="farm_manager",
        blank=True,
        null=True,
        verbose_name=_("Manager"),
    )
    latitude = models.CharField(_("Longitude"), max_length=100, blank=True, null=True)
    longitude = models.CharField(_("Latitude"), max_length=100, blank=True, null=True)
    location = models.OneToOneField(
        Address,
        on_delete=models.CASCADE,
        related_name="farm_address",
        blank=True,
        null=True,
        verbose_name=_("Address"),
    )
    size_hc = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=_("Size")
    )
    departments = models.ManyToManyField(
        "Department", related_name="departments", verbose_name=_("Department")
    )

    class Meta:
        verbose_name = _("Farm")
        verbose_name_plural = _("Farms")
        ordering = ["-created_at"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("farm:farm_detail", kwargs={"pk": self.id})


class Department(Base, models.Model):
    department = models.CharField(_("Department"), max_length=50)
    description = models.TextField(_("Description"))

    class Meta:
        verbose_name = _("Department")
        verbose_name_plural = _("Departments")
        ordering = ["-created_at"]

    def __str__(self):
        return self.department

    def get_absolute_url(self):
        return reverse("farm:department_detail", kwargs={"pk": self.id})

apps/farm/forms.py
from django.forms import ModelForm
from apps.farm.models import Farm, Department

class FarmForm(ModelForm):
    class Meta:
        model = Farm
        fields = ('name','owner','manager','latitude','longitude','location','size_hc', 'departments',)


class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        fields = ('department', 'description',)

apps/farm/templates/farm/farm_detail.html
<h1>Detalhes</h1>
    <ul>
        <li>Nome: {{ object.name }}</li>
        <li>Proprietario: {{ object.owner }}</li>
        <li>Gerente: {{ object.manager }}</li>
        <li>Localização: {{ object.location }}</li>
        <li>Tamanho HC: {{ object.size_hc }}</li>
        <li>Lat/Long: {{ object.latitude }} - {{ object.longitute }}</li>
    </ul>

apps/farm/templates/farm/farm_form.html
<form  method="post" action=".">

    {% csrf_token %}
    {{ form }}
    <input type="submit"> Salvar</button>

</form>

apps/farm/templates/farm/farm_list.html
<style>
    li {
        box-sizing: border-box;
        padding-bottom: 20px;
    }
</style>

<table>
    <thead>
        <th>Nome</th>
        <th>Proprietario</th>
        <th>Gerente</th>
        <th>Localização</th>
        <th>Tamanho</th>
        <th>latitude/longitude</th>
        <th>Departamentos</th>
        <th>Ações</th>
    </thead>
    <tbody>
        {% for farm in object_list %}
        <tr>
            <td>{{ farm.name }}</td>
            <td>{{ farm.owner }}</td>
            <td>{{ farm.manager }}</td>
            <td>{{ farm.location }}</td>
            <td>{{ farm.size_hc }}</td>
            <td>{{ farm.latitude }} - {{ farm.longitude }}</td>
            <td>
                <ul>
                    {% for department in farm.departments.all %}
                        <li> {{ department }} </li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <a href="{% url 'farm:farm_update' farm.pk %}" ><strong>EDIT</strong></a>
                <a href="{% url 'farm:farm_delete' farm.pk %}" ><strong>DELETE</strong></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>