apps/person/urls.py
from django.urls import path
from apps.person.views.person import person
from apps.person.views.email import email
from apps.person.views.phone import phone

app_name = 'person'

urlpatterns = [
    path('person/list/', person.PersonListView.as_view(), name='person_list'),
    path('person/create/', person.PersonCreateView.as_view(), name='person_create'),    
    path('person/<uuid:pk>/update/', person.PersonUpdateView.as_view(), name='person_update'),
    path('person/<uuid:pk>/delete/', person.PersonDeleteView.as_view(), name='person_delete'),
    path('person/<uuid:pk>/detail/', person.PersonDetailView.as_view(), name='person_detail'),
    path('email/list/', email.EmailListView.as_view(), name='email_list'),
    path('email/create/', email.EmailCreateView.as_view(), name='email_create'),    
    path('email/<uuid:pk>/update/', email.EmailUpdateView.as_view(), name='email_update'),
    path('email/<uuid:pk>/delete/', email.EmailDeleteView.as_view(), name='email_delete'),
    path('email/<uuid:pk>/detail/', email.EmailDetailView.as_view(), name='email_detail'),
    path('phone/list/', phone.PhoneListView.as_view(), name='phone_list'),
    path('phone/create/', phone.PhoneCreateView.as_view(), name='phone_create'),    
    path('phone/<uuid:pk>/update/', phone.PhoneUpdateView.as_view(), name='phone_update'),
    path('phone/<uuid:pk>/delete/', phone.PhoneDeleteView.as_view(), name='phone_delete'),
    path('phone/<uuid:pk>/detail/', phone.PhoneDetailView.as_view(), name='phone_detail'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("", include("apps.address.urls")),
    path("", include("apps.person.urls")),
    path("", include("apps.farm.urls")),
    path("", include("apps.employee.urls")),
    path("", include("apps.workshop.urls")),
    path("", include("apps.vehicle.urls")),
    path("", include("apps.inventory.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/person/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.core.models import Base
from django.urls import reverse
from django.db.models import UniqueConstraint
from .choices import CONTACT_TYPE
from ..address.models import Address


class Person(Base, models.Model):
    name = models.CharField(_("Full Name"), max_length=200)
    document = models.CharField(
        _("Document CPF/CNPJ"), max_length=14, null=True, blank=True, unique=True
    )
    rg = models.CharField(_("RG"), max_length=30, null=True, blank=True)
    birth_date = models.DateField(_("Birth Date"), null=True, blank=True)
    addresses = models.ForeignKey(
        Address,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="persons_addresses",
    )

    class Meta:
        verbose_name = _("Person")
        verbose_name_plural = _("Persons")
        ordering = ["-created_at"]
        constraints = [
            UniqueConstraint(
                "name",
                "document",
                name="unique_name_document",
            ),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("person:person_detail", kwargs={"pk": self.id})


class Email(Base, models.Model):
    email = models.EmailField(_("E-mail"), blank=True, null=True, unique=True)
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name="person_email"
    )
    type = models.CharField(
        _("E-mail Type"), max_length=14, choices=CONTACT_TYPE, default="1"
    )

    class Meta:
        verbose_name = _("E-mail")
        verbose_name_plural = _("E-mails")
        ordering = ["-created_at"]

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse("person:email_detail", kwargs={"pk": self.pk})


class Phone(Base, models.Model):
    phone = models.CharField(
        _("Number contact"), max_length=14, blank=True, null=True, unique=True
    )
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name="person_phone"
    )
    type = models.CharField(
        _("Phone Type"), max_length=2, choices=CONTACT_TYPE, default="1"
    )

    class Meta:
        verbose_name = _("Phone")
        verbose_name_plural = _("Phones")
        ordering = ["-created_at"]

    def __str__(self):
        return self.phone

    def get_absolute_url(self):
        return reverse("person:phone_detail", kwargs={"pk": self.pk})

apps/person/forms.py
from django.forms import ModelForm
from apps.person.models import Person, Email, Phone

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ('name','document','rg','birth_date','addresses',)

class EmailForm(ModelForm):
    class Meta:
        model = Email
        fields = ('email','person','type',)

class PhoneForm(ModelForm):
    class Meta:
        model = Phone
        fields = ('phone','person','type',)

apps/person/templates/person/person_detail.html
<h1>Detalhes</h1>
    <ul>
        <li>Logradouro: {{ object.logradouro }}</li>
        <li>Numero: {{ object.number }}</li>
        <li>CEP: {{ object.zipcode }}</li>
        <li>Bairro: {{ object.neighborhood }}</li>
        <li>Cidade: {{ object.city }}</li>
    </ul>

apps/person/templates/person/person_form.html
<form  method="post" action=".">

    {% csrf_token %}
    {{ form }}
    <input type="submit"> Salvar</button>

</form>

apps/person/templates/person/person_list.html
<style>
    li {
        box-sizing: border-box;
        padding-bottom: 20px;
    }
</style>

<table>
    <thead>
        <th>Nome</th>
        <th>Número</th>
        <th>CEP</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Ações</th>
    </thead>
    <tbody>
        {% for person in object_list %}
        <tr>
            <td>{{ person.name }}</td>
            <td>{{ person.document }}</td>
            <td>{{ person.rg }}</td>
            <td>{{ person.birth_date }}</td>
            <td>{{ person.addresses }}</td>
            <td>{{ person.phone }}</td>
            <td>{{ person.email }}</td>
            <td>
                <a href="{% url 'person:person_update' person.pk %}" ><strong>EDIT</strong></a>
                <a href="{% url 'person:person_delete' person.pk %}" ><strong>DELETE</strong></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>